### ISSUE TITLE
Xaml parse failed when trying to open BindingPage

### ISSUE THREAD

**Issue by jkommeren** [Microsoft/XamlIslandBlogPostSample#1]
VS2017 15.8.9
October build
SDK 17763
.Net 4.7.2

Stacktrace: "   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)\r\n   at UWPClassLibrary.Controls.BindingSamplePage.InitializeComponent() in C:\\Users\\joris\\Downloads\\XamlIslandBlogPostSample-master\\UWPClassLibrary\\obj\\Debug\\Controls\\BindingSamplePage.g.i.cs:line 33\r\n   at UWPClassLibrary.Controls.BindingSamplePage..ctor() in C:\\Users\\joris\\Downloads\\XamlIslandBlogPostSample-master\\UWPClassLibrary\\Controls\\BindingSamplePage.xaml.cs:line 34"

When I comment this line out:  bindingSamplePage.ViewModel = ViewModel;

It does not crash

**Comment by azchohfi** [comment]
What is the exception?

**Comment by jkommeren** [comment]
It was "Xaml parsing failed"

Although now I reenabled the line, and it continued to work fine. Not sure what happened here! Can't reproduce it anymore :)

**Comment by azchohfi** [comment]
It is probably the target file. You need to build the UWP Class Library once, and reload the WPF project. That will add the build generated files to the WPF project.
